config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :merchants

  root to: 'home#index'

  namespace :admins do
    resources :merchants
    resources :transactions, only: [:index]
  end

  namespace :merchants do
    resources :transactions, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'Merchant', at: 'auth', controllers: {
        sessions: 'api/v1/sessions'
      }
      resources :payments, only: [:create]
    end
  end
end

app/models/merchant.rb
# frozen_string_literal: true

class Merchant < ApplicationRecord
  devise :database_authenticatable
  include DeviseTokenAuth::Concerns::User

  enum status: {
    active: 'active',
    inactive: 'inactive'
  }

  has_many :transactions,
           class_name: 'Transactions::Base',
           dependent: :restrict_with_exception

  validates :email,
            presence: true,
            uniqueness: true
  validates :name,
            presence: true

  # rubocop:disable Rails/SkipsModelValidations
  # Valid Rails-way for atomic update numeric column
  def increment_total_transaction_sum(by)
    Merchant.update_counters(id, total_transaction_sum: by)
  end
  # rubocop:enable Rails/SkipsModelValidations
end

app/controllers/admins/merchants_controller.rb
# frozen_string_literal: true

module Admins
  class MerchantsController < ApplicationController
    def index
      call_operation(Admins::Merchants::Index, user: current_admin) do |op|
        @presenter = op.presenter
      end
    end

    def new
      call_operation(Admins::Merchants::New, user: current_admin) do |op|
        @merchant = op.contract
      end
    end

    def edit
      call_operation(Admins::Merchants::Edit, user: current_admin, params: params) do |op|
        @merchant = op.contract
      end
    end

    def create
      call_operation(Admins::Merchants::Create, user: current_admin, params: merchant_params) do |op|
        op.success { redirect_to admins_merchants_path, flash: { success: t('controllers.create.flash.success') } }
        op.failure do
          @merchant = op.contract
          flash.now[:error] = t('controllers.create.flash.error')
          render :new
        end
      end
    end

    def update
      call_operation(Admins::Merchants::Update, user: current_admin, params: merchant_params) do |op|
        op.success { redirect_to admins_merchants_path, flash: { success: t('controllers.update.flash.success') } }
        op.failure do
          @merchant = op.contract
          flash.now[:error] = t('controllers.update.flash.error')
          render :edit
        end
      end
    end

    def destroy
      call_operation(Admins::Merchants::Destroy, user: current_admin, params: params) do |op|
        op.success { redirect_to admins_merchants_path, flash: { success: t('controllers.destroy.success') } }
        op.failure { redirect_to admins_merchants_path, flash: { error: op.errors.full_messages } }
      end
    end

    def merchant_params
      params.require(:merchant).permit(
        :id,
        :email,
        :name,
        :description
      )
    end
  end
end

app/controllers/merchants/application_controller.rb
# frozen_string_literal: true

module Merchants
  class ApplicationController < ApplicationController
    before_action :authenticate_merchant!
  end
end

app/controllers/merchants/transactions_controller.rb
# frozen_string_literal: true

module Merchants
  class TransactionsController < ApplicationController
    def index
      call_operation(Merchants::Transactions::Index, user: current_merchant, params: params) do |op|
        @presenter = op.presenter
      end
    end
  end
end

app/views/admins/merchants/edit.html.slim
.row
  .col-md-8
    = form_for(@merchant, url: admins_merchant_path(@merchant)) do |f|
      = f.hidden_field :id
      .form-group
        = f.label :email
        = f.text_field :email, class: 'form-control'
        - with_each_field_error(@merchant, :email) do |message|
          .invalid-feedback = message
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
        - with_each_field_error(@merchant, :name) do |message|
          .invalid-feedback = message
      .form-group
        = f.label :description
        = f.text_area :description, rows: 4, class: "form-control"
      = f.submit class: 'btn btn-primary'

app/views/admins/merchants/index.html.slim
table.table.table-striped
  thead.thead-dark
    tr
      th Email
      th Name
      th Description
      th Balance
      th Created
      th Transactions
      th Actions
  - @presenter.merchants.each do |t|
    tr
      td.align-middle
        = t[:email]
      td.align-middle
        = t[:name]
      td.align-middle
        = truncate(t[:description])
      td.align-middle
        = number_to_currency(t[:balance])
      td.align-middle
        = time_ago_in_words(t[:created_at])
      td.align-middle
        a href=admins_transactions_path(merchant_id: t[:id]) Transactions
      td
        a.btn.btn-success href=edit_admins_merchant_path(id: t[:id]) Edit
        = button_to("Destroy",  admins_merchant_path(id: t[:id]), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger', form_class: 'd-inline')

app/views/admins/merchants/new.html.slim
.row
  .col-md-8
    = form_for(@merchant, url: admins_merchants_path) do |f|
      .form-group
        = f.label :email
        = f.text_field :email, class: 'form-control'
        - with_each_field_error(@merchant, :email) do |message|
          .invalid-feedback = message
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
        - with_each_field_error(@merchant, :name) do |message|
          .invalid-feedback = message
      .form-group
        = f.label :description
        = f.text_area :description, rows: 4, class: "form-control"
      = f.submit class: 'btn btn-primary'