config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :merchants

  root to: 'home#index'

  namespace :admins do
    resources :merchants
    resources :transactions, only: [:index]
  end

  namespace :merchants do
    resources :transactions, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      mount_devise_token_auth_for 'Merchant', at: 'auth', controllers: {
        sessions: 'api/v1/sessions'
      }
      resources :payments, only: [:create]
    end
  end
end

app/views/layouts/_alerts.html.slim
- with_each_flash_message(flash) do |alert_class, v|
  div class=alert_class role="alert"
    = v

app/views/layouts/_nav-bar.html.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  a.navbar-brand href=root_path PayPost
  button.navbar-toggler aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarsExampleDefault" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarsExampleDefault.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      - if admin_signed_in?
        li.nav-item class=('active' if nav_active?(controller: 'admins/merchants'))
          a.nav-link href=admins_merchants_path Merchants
      - if merchant_signed_in?
        li.nav-item class=('active' if nav_active?(controller: 'merchants/transactions'))
          a.nav-link href=merchants_transactions_path Transactions
    ul.navbar-nav.ml-auto
      - if merchant_signed_in? || admin_signed_in?
        li.nav-item
          = link_to 'Sign Out', destroy_merchant_session_path, method: :delete, class: 'nav-link'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PayPost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/nav-bar' %>
    <div class="container pt-4">
      <%= render 'layouts/alerts' %>
      <%= yield %>
    </div>
  </body>
</html>